[tox]
envlist = py{311,312}-django42, quality
skipsdist = true

[testenv]
deps =
    django42: Django>=4.2,<5.0
    -r requirements/test.txt
commands =
    pytest {posargs}

[testenv:quality]
deps = ruff
commands =
    ruff check openedx_mcp tests
